spring:
  application:
    name: registration-server

registraton:
  server:
    endpoint: http://registration-server

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env,health